### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by IanLulu** [IanLulu/Conways-Game-of-Life#1]
Sources:
- https://www.cs.cmu.edu/afs/cs/project/ai-repository/ai/lang/lisp/code/fun/life.cl
- https://www.cs.cmu.edu/afs/cs/project/ai-repository/ai/lang/lisp/code/fun/
- https://www.cs.cmu.edu/afs/cs.cmu.edu/project/ai-repository/ai/0.html

To implement:
- [ ] add common lisp logo
- [ ] add lain ep 7 screenshot
- [ ] add detail about how this code is from 1995 and couldve been used by the creators of the show used this exact webpage as reference
- [ ] add some easter egg to knights of lambda calculus and eastern calculus

✌️
